/**
 * The watercolour filters shared by every painted scene (spec 19), defined once on the page:
 * `wcBig` (sky and land washes: displaced edges, blotchy pigment and a darker dried edge), `wcSky`
 * (soft sky washes), `wcMid` (buildings, hills, kites), `wcFig` (figures), `wcInk` (dry-brush
 * lines), `wcBloom` (glows), `wcFeather`/`wcFeatherS` (the painted vignette) and `wcPaper` (grain).
 * Two octaves of turbulence at most, regions close to the object, nothing animated.
 */
export const WATERCOLOUR_FILTERS =
  '<filter id="wcBig" x="-25%" y="-25%" width="150%" height="150%" color-interpolation-filters="sRGB"><feTurbulence type="fractalNoise" baseFrequency=".009" numOctaves="3" seed="2" result="t"/><feDisplacementMap in="SourceGraphic" in2="t" scale="44" xChannelSelector="R" yChannelSelector="G" result="d"/><feGaussianBlur in="d" stdDeviation="2.4" result="b"/><feTurbulence type="fractalNoise" baseFrequency=".022" numOctaves="2" seed="7" result="t2"/><feColorMatrix in="t2" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 -1.5 1.25" result="m"/><feComposite in="b" in2="m" operator="in" result="p"/><feComponentTransfer in="b" result="base"><feFuncA type="linear" slope=".6"/></feComponentTransfer><feMorphology in="d" operator="erode" radius="2.2" result="e"/><feComposite in="d" in2="e" operator="out" result="r"/><feGaussianBlur in="r" stdDeviation="1" result="r2"/><feComponentTransfer in="r2" result="r3"><feFuncA type="linear" slope=".45"/></feComponentTransfer><feMerge><feMergeNode in="base"/><feMergeNode in="p"/><feMergeNode in="r3"/></feMerge></filter>' +
  '<filter id="wcSky" x="-25%" y="-25%" width="150%" height="150%" color-interpolation-filters="sRGB"><feTurbulence type="fractalNoise" baseFrequency=".008" numOctaves="2" seed="3" result="t"/><feDisplacementMap in="SourceGraphic" in2="t" scale="50" xChannelSelector="R" yChannelSelector="G" result="d"/><feGaussianBlur in="d" stdDeviation="12" result="b"/><feTurbulence type="fractalNoise" baseFrequency=".018" numOctaves="2" seed="11" result="t2"/><feColorMatrix in="t2" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 -1.1 1.1" result="m"/><feComposite in="b" in2="m" operator="in"/></filter>' +
  '<filter id="wcMid" x="-15%" y="-15%" width="130%" height="130%" color-interpolation-filters="sRGB"><feTurbulence type="fractalNoise" baseFrequency=".03" numOctaves="2" seed="4" result="t"/><feDisplacementMap in="SourceGraphic" in2="t" scale="9" xChannelSelector="R" yChannelSelector="G" result="d"/><feGaussianBlur in="d" stdDeviation=".7" result="b"/><feTurbulence type="fractalNoise" baseFrequency=".06" numOctaves="2" seed="13" result="t2"/><feColorMatrix in="t2" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 -2.4 1.7" result="m"/><feComposite in="b" in2="m" operator="in" result="p"/><feComponentTransfer in="b" result="base"><feFuncA type="linear" slope=".6"/></feComponentTransfer><feMorphology in="d" operator="erode" radius="1.3" result="e"/><feComposite in="d" in2="e" operator="out" result="r"/><feComponentTransfer in="r" result="r3"><feFuncA type="linear" slope=".75"/></feComponentTransfer><feMerge><feMergeNode in="base"/><feMergeNode in="p"/><feMergeNode in="r3"/></feMerge></filter>' +
  '<filter id="wcFig" x="-20%" y="-20%" width="140%" height="140%" color-interpolation-filters="sRGB"><feTurbulence type="fractalNoise" baseFrequency=".09" numOctaves="2" seed="8" result="t"/><feDisplacementMap in="SourceGraphic" in2="t" scale="2.4" xChannelSelector="R" yChannelSelector="G" result="d"/><feColorMatrix in="t" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 -1.6 1.55" result="m"/><feComposite in="d" in2="m" operator="in" result="p"/><feComponentTransfer in="d" result="base"><feFuncA type="linear" slope=".9"/></feComponentTransfer><feMorphology in="d" operator="erode" radius=".7" result="e"/><feComposite in="d" in2="e" operator="out" result="r"/><feMerge><feMergeNode in="base"/><feMergeNode in="p"/><feMergeNode in="r"/></feMerge></filter>' +
  '<filter id="wcInk" x="-10%" y="-10%" width="120%" height="120%"><feTurbulence type="fractalNoise" baseFrequency=".25" numOctaves="1" seed="3" result="t"/><feDisplacementMap in="SourceGraphic" in2="t" scale="1.6" xChannelSelector="R" yChannelSelector="G"/></filter>' +
  '<filter id="wcBloom" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="10"/></filter>' +
  '<filter id="wcFeather" x="-15%" y="-15%" width="130%" height="130%"><feTurbulence type="fractalNoise" baseFrequency=".011" numOctaves="3" seed="5" result="t"/><feDisplacementMap in="SourceGraphic" in2="t" scale="90" xChannelSelector="R" yChannelSelector="G" result="d"/><feGaussianBlur in="d" stdDeviation="22"/></filter>' +
  '<filter id="wcFeatherS" x="-15%" y="-15%" width="130%" height="130%"><feTurbulence type="fractalNoise" baseFrequency=".02" numOctaves="3" seed="5" result="t"/><feDisplacementMap in="SourceGraphic" in2="t" scale="16" xChannelSelector="R" yChannelSelector="G" result="d"/><feGaussianBlur in="d" stdDeviation="9"/></filter>' +
  '<filter id="wcPaper" x="0" y="0" width="100%" height="100%"><feTurbulence type="fractalNoise" baseFrequency=".75" numOctaves="2" seed="21" stitchTiles="stitch"/><feColorMatrix values="0 0 0 0 .35  0 0 0 0 .28  0 0 0 0 .2  0 0 0 .7 -.22"/><feComposite in2="SourceAlpha" operator="in"/></filter>';
