// Writes the greeting assets from scenes.js: node design/brand/greeting/export.js
// SVG scenes (light/dark), 24px icons, and PNG renders (1200×320 @1x and @2x, transparent outside the drawing) when Playwright is available.
const fs = require('fs'), path = require('path');
const G = require('./scenes.js'), out = __dirname;
const files = [];
for (const p of G.PERIODS) for (const [t, P] of [['light', G.LIGHT], ['dark', G.DARK]]) {
  const svg = G.greetScene(p.k, `gs-${p.k}-${t}`, P, {cls: '', size: [1200, 320]}).replace(' class="ms-sun gs-body"', '').replace(/ class="ms-sun gs-body"/g, '').replace(/ class="gs-star"/g, '').replace(/ style="animation-delay:[^"]*"/g, '');
  const f = `${p.k}-${t}.svg`; fs.writeFileSync(path.join(out, f), `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Quad greeting scene: ${p.label} (${t}). Generated by export.js from scenes.js. -->\n${svg}\n`); files.push(f);
}
for (const p of G.PERIODS) { const f = `icon-${p.k}.svg`; fs.writeFileSync(path.join(out, f), G.greetIcon(p.k, 'currentColor', 24) + '\n'); files.push(f); }
console.log('wrote', files.join(', '));
(async () => {
  let chromium; try { ({chromium} = require(process.env.PW_PATH || 'playwright')); } catch (e) { console.log('Playwright not found: skipping PNG renders'); return; }
  const b = await chromium.launch(process.env.PW_CHROME ? {executablePath: process.env.PW_CHROME} : {});
  for (const scale of [1, 2]) { const pg = await (await b.newContext({viewport: {width: 1200, height: 320}, deviceScaleFactor: scale})).newPage();
    for (const p of G.PERIODS) for (const t of ['light', 'dark']) { await pg.goto('file://' + path.join(out, `${p.k}-${t}.svg`)); await pg.screenshot({path: path.join(out, 'png', `${p.k}-${t}${scale === 2 ? '@2x' : ''}.png`), omitBackground: true}); } }
  await b.close(); console.log('wrote PNG renders to png/');
})();
