-- Hand-added (bootstrap): extensions, schema access and default privileges live in the migration,
-- not only in docker/postgres/init, because pg_default_acl is per database and per schema: a fresh
-- test database or a `db:reset` (drop schema public) would otherwise lose them.
CREATE EXTENSION IF NOT EXISTS citext;--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS pg_trgm;--> statement-breakpoint
REVOKE CREATE ON SCHEMA public FROM PUBLIC;--> statement-breakpoint
GRANT USAGE ON SCHEMA public TO quad_app, quad_platform;--> statement-breakpoint
ALTER DEFAULT PRIVILEGES FOR ROLE quad_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO quad_app, quad_platform;--> statement-breakpoint
ALTER DEFAULT PRIVILEGES FOR ROLE quad_owner IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO quad_app, quad_platform;--> statement-breakpoint
-- Generated by drizzle-kit:
CREATE TYPE "public"."school_health_level" AS ENUM('thriving', 'watch', 'at_risk', 'paused');--> statement-breakpoint
CREATE TYPE "public"."tenant_region" AS ENUM('ap-south', 'me-central', 'ap-southeast');--> statement-breakpoint
CREATE TYPE "public"."tenant_status" AS ENUM('trial', 'onboarding', 'active', 'past_due', 'suspended', 'deleted');--> statement-breakpoint
CREATE TABLE "tenants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"short_name" varchar(4) NOT NULL,
	"slug" text NOT NULL,
	"country" char(2) NOT NULL,
	"region" "tenant_region" DEFAULT 'ap-south' NOT NULL,
	"time_zone" text NOT NULL,
	"currency" char(3) NOT NULL,
	"locale" text NOT NULL,
	"status" "tenant_status" DEFAULT 'trial' NOT NULL,
	"plan_id" uuid,
	"seat_limit" integer,
	"trial_ends_at" timestamp with time zone,
	"curriculum_template_id" uuid,
	"since" date,
	"health_override" "school_health_level",
	"suspended_at" timestamp with time zone,
	"suspend_reason" text,
	"deletion_scheduled_for" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tenants_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
-- Hand-added (grants): tenants is a platform table (spec 02, Tenancy). Only quad_platform
-- (withPlatform) reads and writes it; quad_app gets nothing. Foreign keys from tenant tables
-- still work because Postgres runs referential checks as the referenced table's owner.
GRANT SELECT, INSERT, UPDATE, DELETE ON "tenants" TO quad_platform;--> statement-breakpoint
REVOKE ALL ON "tenants" FROM quad_app;
