// GENERATED by pnpm tokens:build — do not edit

import 'package:flutter/material.dart';

/// Shape, space, elevation and font names. Colours live in [QuadColors].
class QuadTokens {
  const QuadTokens._();

  static const double radiusCard = 16;
  static const double radiusScene = 24;
  static const double radiusInput = 12;
  static const double radiusPill = 999;

  static const List<double> spacing = [
    4,
    6,
    8,
    10,
    12,
    14,
    16,
    18,
    20,
    24,
    28,
    32,
  ];

  static const List<BoxShadow> shadowCard = [
    BoxShadow(color: Color(0x0D1C1B2E), blurRadius: 2, offset: Offset(0, 1)),
    BoxShadow(
      color: Color(0x2E1C1B2E),
      blurRadius: 24,
      spreadRadius: -12,
      offset: Offset(0, 8),
    ),
  ];
  static const List<BoxShadow> shadowLg = [
    BoxShadow(
      color: Color(0x591C1B2E),
      blurRadius: 60,
      spreadRadius: -18,
      offset: Offset(0, 24),
    ),
  ];

  static const String fontSans = 'Figtree';
  static const String fontAccent = 'Fraunces';
}

/// Every colour of the Quad design system, one instance per theme.
/// Read it with `Theme.of(context).extension<QuadColors>()!`.
@immutable
class QuadColors extends ThemeExtension<QuadColors> {
  const QuadColors({
    required this.canvas,
    required this.surface,
    required this.surface2,
    required this.line,
    required this.lineStrong,
    required this.ink,
    required this.ink2,
    required this.ink3,
    required this.brand,
    required this.brandStrong,
    required this.brandSoft,
    required this.brandInk,
    required this.brandFill,
    required this.brandFillStrong,
    required this.rail,
    required this.rail2,
    required this.railInk,
    required this.railInk2,
    required this.railActive,
    required this.good,
    required this.goodSoft,
    required this.warn,
    required this.warnSoft,
    required this.bad,
    required this.badSoft,
    required this.info,
    required this.infoSoft,
    required this.c1,
    required this.c2,
    required this.c3,
    required this.c4,
    required this.c5,
    required this.gold,
    required this.goldSoft,
    required this.band,
    required this.band2,
    required this.bandInk,
    required this.bandInk2,
    required this.bandLine,
    required this.bandTagTealBg,
    required this.bandTagTealInk,
    required this.bandTagCoralBg,
    required this.bandTagCoralInk,
    required this.bandTagAmberBg,
    required this.bandTagAmberInk,
    required this.bandTagLilacBg,
    required this.bandTagLilacInk,
    required this.heat0,
    required this.heat1,
    required this.heat2,
    required this.heat3,
  });

  final Color canvas;
  final Color surface;
  final Color surface2;
  final Color line;
  final Color lineStrong;
  final Color ink;
  final Color ink2;
  final Color ink3;
  final Color brand;
  final Color brandStrong;
  final Color brandSoft;
  final Color brandInk;
  final Color brandFill;
  final Color brandFillStrong;
  final Color rail;
  final Color rail2;
  final Color railInk;
  final Color railInk2;
  final Color railActive;
  final Color good;
  final Color goodSoft;
  final Color warn;
  final Color warnSoft;
  final Color bad;
  final Color badSoft;
  final Color info;
  final Color infoSoft;
  final Color c1;
  final Color c2;
  final Color c3;
  final Color c4;
  final Color c5;
  final Color gold;
  final Color goldSoft;
  final Color band;
  final Color band2;
  final Color bandInk;
  final Color bandInk2;
  final Color bandLine;
  final Color bandTagTealBg;
  final Color bandTagTealInk;
  final Color bandTagCoralBg;
  final Color bandTagCoralInk;
  final Color bandTagAmberBg;
  final Color bandTagAmberInk;
  final Color bandTagLilacBg;
  final Color bandTagLilacInk;
  final Color heat0;
  final Color heat1;
  final Color heat2;
  final Color heat3;

  static const light = QuadColors(
    canvas: Color(0xFFFAF8F5),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFF6F3EF),
    line: Color(0xFFECE8E3),
    lineStrong: Color(0xFFDCD6CF),
    ink: Color(0xFF1C1B2E),
    ink2: Color(0xFF4E4C63),
    ink3: Color(0xFF7D7A90),
    brand: Color(0xFFDD4A42),
    brandStrong: Color(0xFFC23B34),
    brandSoft: Color(0xFFFDE7E5),
    brandInk: Color(0xFFFFFFFF),
    brandFill: Color(0xFFD0463E),
    brandFillStrong: Color(0xFFA63832),
    rail: Color(0xFF1F2559),
    rail2: Color(0xFF2C3370),
    railInk: Color(0xFFE6E7F5),
    railInk2: Color(0xFFA3A6CC),
    railActive: Color(0xFFDD4A42),
    good: Color(0xFF1F8A5B),
    goodSoft: Color(0xFFE3F4EC),
    warn: Color(0xFFB26A00),
    warnSoft: Color(0xFFFFF1DC),
    bad: Color(0xFFD13A3A),
    badSoft: Color(0xFFFDE6E6),
    info: Color(0xFF6D5AE6),
    infoSoft: Color(0xFFEEEAFE),
    c1: Color(0xFFE5534B),
    c2: Color(0xFF3B4AA8),
    c3: Color(0xFF8B7CF6),
    c4: Color(0xFFF2A93B),
    c5: Color(0xFF2BB0A0),
    gold: Color(0xFF8B7CF6),
    goldSoft: Color(0xFFEEEAFE),
    band: Color(0xFF1A2A5E),
    band2: Color(0xFF24387A),
    bandInk: Color(0xFFF3F2FB),
    bandInk2: Color(0xFFCDD5F2),
    bandLine: Color(0xFF34498F),
    bandTagTealBg: Color(0xFF1D4F4A),
    bandTagTealInk: Color(0xFF9BEADF),
    bandTagCoralBg: Color(0xFF5A2430),
    bandTagCoralInk: Color(0xFFFFC3BC),
    bandTagAmberBg: Color(0xFF5A4317),
    bandTagAmberInk: Color(0xFFFFDDA1),
    bandTagLilacBg: Color(0xFF3A3170),
    bandTagLilacInk: Color(0xFFD9D2FF),
    heat0: Color(0xFFF7CBC9),
    heat1: Color(0xFFBFE7E3),
    heat2: Color(0xFF80D0C6),
    heat3: Color(0xFF2BB0A0),
  );

  static const dark = QuadColors(
    canvas: Color(0xFF13142A),
    surface: Color(0xFF1B1D3A),
    surface2: Color(0xFF22254A),
    line: Color(0xFF2E3260),
    lineStrong: Color(0xFF3D4277),
    ink: Color(0xFFF1F1FA),
    ink2: Color(0xFFC4C5DD),
    ink3: Color(0xFF9395B5),
    brand: Color(0xFFFF7A6E),
    brandStrong: Color(0xFFFF978C),
    brandSoft: Color(0xFF3D1F2A),
    brandInk: Color(0xFF1B1D3A),
    brandFill: Color(0xFFFF7A6E),
    brandFillStrong: Color(0xFFFF978C),
    rail: Color(0xFF0E0F22),
    rail2: Color(0xFF2C3370),
    railInk: Color(0xFFE6E7F5),
    railInk2: Color(0xFFA3A6CC),
    railActive: Color(0xFFFF7A6E),
    good: Color(0xFF4CC992),
    goodSoft: Color(0xFF123326),
    warn: Color(0xFFF0B357),
    warnSoft: Color(0xFF3A2A10),
    bad: Color(0xFFFF7A7A),
    badSoft: Color(0xFF3D1A1E),
    info: Color(0xFFA99BFF),
    infoSoft: Color(0xFF262046),
    c1: Color(0xFFFF7A6E),
    c2: Color(0xFF7B8BF0),
    c3: Color(0xFFA99BFF),
    c4: Color(0xFFF5B95A),
    c5: Color(0xFF3CC7B5),
    gold: Color(0xFFA99BFF),
    goldSoft: Color(0xFF262046),
    band: Color(0xFF0F0F13),
    band2: Color(0xFF1D1D23),
    bandInk: Color(0xFFF3F2FB),
    bandInk2: Color(0xFFD0CFCA),
    bandLine: Color(0xFF33333C),
    bandTagTealBg: Color(0xFF1D4F4A),
    bandTagTealInk: Color(0xFF9BEADF),
    bandTagCoralBg: Color(0xFF5A2430),
    bandTagCoralInk: Color(0xFFFFC3BC),
    bandTagAmberBg: Color(0xFF5A4317),
    bandTagAmberInk: Color(0xFFFFDDA1),
    bandTagLilacBg: Color(0xFF3A3170),
    bandTagLilacInk: Color(0xFFD9D2FF),
    heat0: Color(0xFF5F394A),
    heat1: Color(0xFF25505F),
    heat2: Color(0xFF2F8384),
    heat3: Color(0xFF3CC7B5),
  );

  /// Console overrides: the console has its own, darker rail.
  static const consoleLight = QuadColors(
    canvas: Color(0xFFFAF8F5),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFF6F3EF),
    line: Color(0xFFECE8E3),
    lineStrong: Color(0xFFDCD6CF),
    ink: Color(0xFF1C1B2E),
    ink2: Color(0xFF4E4C63),
    ink3: Color(0xFF7D7A90),
    brand: Color(0xFFDD4A42),
    brandStrong: Color(0xFFC23B34),
    brandSoft: Color(0xFFFDE7E5),
    brandInk: Color(0xFFFFFFFF),
    brandFill: Color(0xFFD0463E),
    brandFillStrong: Color(0xFFA63832),
    rail: Color(0xFF15173A),
    rail2: Color(0xFF23265A),
    railInk: Color(0xFFE6E7F5),
    railInk2: Color(0xFFA3A6CC),
    railActive: Color(0xFF6D5AE6),
    good: Color(0xFF1F8A5B),
    goodSoft: Color(0xFFE3F4EC),
    warn: Color(0xFFB26A00),
    warnSoft: Color(0xFFFFF1DC),
    bad: Color(0xFFD13A3A),
    badSoft: Color(0xFFFDE6E6),
    info: Color(0xFF6D5AE6),
    infoSoft: Color(0xFFEEEAFE),
    c1: Color(0xFFE5534B),
    c2: Color(0xFF3B4AA8),
    c3: Color(0xFF8B7CF6),
    c4: Color(0xFFF2A93B),
    c5: Color(0xFF2BB0A0),
    gold: Color(0xFF8B7CF6),
    goldSoft: Color(0xFFEEEAFE),
    band: Color(0xFF1A2A5E),
    band2: Color(0xFF24387A),
    bandInk: Color(0xFFF3F2FB),
    bandInk2: Color(0xFFCDD5F2),
    bandLine: Color(0xFF34498F),
    bandTagTealBg: Color(0xFF1D4F4A),
    bandTagTealInk: Color(0xFF9BEADF),
    bandTagCoralBg: Color(0xFF5A2430),
    bandTagCoralInk: Color(0xFFFFC3BC),
    bandTagAmberBg: Color(0xFF5A4317),
    bandTagAmberInk: Color(0xFFFFDDA1),
    bandTagLilacBg: Color(0xFF3A3170),
    bandTagLilacInk: Color(0xFFD9D2FF),
    heat0: Color(0xFFF7CBC9),
    heat1: Color(0xFFBFE7E3),
    heat2: Color(0xFF80D0C6),
    heat3: Color(0xFF2BB0A0),
  );

  static const consoleDark = QuadColors(
    canvas: Color(0xFF13142A),
    surface: Color(0xFF1B1D3A),
    surface2: Color(0xFF22254A),
    line: Color(0xFF2E3260),
    lineStrong: Color(0xFF3D4277),
    ink: Color(0xFFF1F1FA),
    ink2: Color(0xFFC4C5DD),
    ink3: Color(0xFF9395B5),
    brand: Color(0xFFFF7A6E),
    brandStrong: Color(0xFFFF978C),
    brandSoft: Color(0xFF3D1F2A),
    brandInk: Color(0xFF1B1D3A),
    brandFill: Color(0xFFFF7A6E),
    brandFillStrong: Color(0xFFFF978C),
    rail: Color(0xFF0C0D20),
    rail2: Color(0xFF23265A),
    railInk: Color(0xFFE6E7F5),
    railInk2: Color(0xFFA3A6CC),
    railActive: Color(0xFF6D5AE6),
    good: Color(0xFF4CC992),
    goodSoft: Color(0xFF123326),
    warn: Color(0xFFF0B357),
    warnSoft: Color(0xFF3A2A10),
    bad: Color(0xFFFF7A7A),
    badSoft: Color(0xFF3D1A1E),
    info: Color(0xFFA99BFF),
    infoSoft: Color(0xFF262046),
    c1: Color(0xFFFF7A6E),
    c2: Color(0xFF7B8BF0),
    c3: Color(0xFFA99BFF),
    c4: Color(0xFFF5B95A),
    c5: Color(0xFF3CC7B5),
    gold: Color(0xFFA99BFF),
    goldSoft: Color(0xFF262046),
    band: Color(0xFF0F0F13),
    band2: Color(0xFF1D1D23),
    bandInk: Color(0xFFF3F2FB),
    bandInk2: Color(0xFFD0CFCA),
    bandLine: Color(0xFF33333C),
    bandTagTealBg: Color(0xFF1D4F4A),
    bandTagTealInk: Color(0xFF9BEADF),
    bandTagCoralBg: Color(0xFF5A2430),
    bandTagCoralInk: Color(0xFFFFC3BC),
    bandTagAmberBg: Color(0xFF5A4317),
    bandTagAmberInk: Color(0xFFFFDDA1),
    bandTagLilacBg: Color(0xFF3A3170),
    bandTagLilacInk: Color(0xFFD9D2FF),
    heat0: Color(0xFF5F394A),
    heat1: Color(0xFF25505F),
    heat2: Color(0xFF2F8384),
    heat3: Color(0xFF3CC7B5),
  );

  @override
  QuadColors copyWith({
    Color? canvas,
    Color? surface,
    Color? surface2,
    Color? line,
    Color? lineStrong,
    Color? ink,
    Color? ink2,
    Color? ink3,
    Color? brand,
    Color? brandStrong,
    Color? brandSoft,
    Color? brandInk,
    Color? brandFill,
    Color? brandFillStrong,
    Color? rail,
    Color? rail2,
    Color? railInk,
    Color? railInk2,
    Color? railActive,
    Color? good,
    Color? goodSoft,
    Color? warn,
    Color? warnSoft,
    Color? bad,
    Color? badSoft,
    Color? info,
    Color? infoSoft,
    Color? c1,
    Color? c2,
    Color? c3,
    Color? c4,
    Color? c5,
    Color? gold,
    Color? goldSoft,
    Color? band,
    Color? band2,
    Color? bandInk,
    Color? bandInk2,
    Color? bandLine,
    Color? bandTagTealBg,
    Color? bandTagTealInk,
    Color? bandTagCoralBg,
    Color? bandTagCoralInk,
    Color? bandTagAmberBg,
    Color? bandTagAmberInk,
    Color? bandTagLilacBg,
    Color? bandTagLilacInk,
    Color? heat0,
    Color? heat1,
    Color? heat2,
    Color? heat3,
  }) {
    return QuadColors(
      canvas: canvas ?? this.canvas,
      surface: surface ?? this.surface,
      surface2: surface2 ?? this.surface2,
      line: line ?? this.line,
      lineStrong: lineStrong ?? this.lineStrong,
      ink: ink ?? this.ink,
      ink2: ink2 ?? this.ink2,
      ink3: ink3 ?? this.ink3,
      brand: brand ?? this.brand,
      brandStrong: brandStrong ?? this.brandStrong,
      brandSoft: brandSoft ?? this.brandSoft,
      brandInk: brandInk ?? this.brandInk,
      brandFill: brandFill ?? this.brandFill,
      brandFillStrong: brandFillStrong ?? this.brandFillStrong,
      rail: rail ?? this.rail,
      rail2: rail2 ?? this.rail2,
      railInk: railInk ?? this.railInk,
      railInk2: railInk2 ?? this.railInk2,
      railActive: railActive ?? this.railActive,
      good: good ?? this.good,
      goodSoft: goodSoft ?? this.goodSoft,
      warn: warn ?? this.warn,
      warnSoft: warnSoft ?? this.warnSoft,
      bad: bad ?? this.bad,
      badSoft: badSoft ?? this.badSoft,
      info: info ?? this.info,
      infoSoft: infoSoft ?? this.infoSoft,
      c1: c1 ?? this.c1,
      c2: c2 ?? this.c2,
      c3: c3 ?? this.c3,
      c4: c4 ?? this.c4,
      c5: c5 ?? this.c5,
      gold: gold ?? this.gold,
      goldSoft: goldSoft ?? this.goldSoft,
      band: band ?? this.band,
      band2: band2 ?? this.band2,
      bandInk: bandInk ?? this.bandInk,
      bandInk2: bandInk2 ?? this.bandInk2,
      bandLine: bandLine ?? this.bandLine,
      bandTagTealBg: bandTagTealBg ?? this.bandTagTealBg,
      bandTagTealInk: bandTagTealInk ?? this.bandTagTealInk,
      bandTagCoralBg: bandTagCoralBg ?? this.bandTagCoralBg,
      bandTagCoralInk: bandTagCoralInk ?? this.bandTagCoralInk,
      bandTagAmberBg: bandTagAmberBg ?? this.bandTagAmberBg,
      bandTagAmberInk: bandTagAmberInk ?? this.bandTagAmberInk,
      bandTagLilacBg: bandTagLilacBg ?? this.bandTagLilacBg,
      bandTagLilacInk: bandTagLilacInk ?? this.bandTagLilacInk,
      heat0: heat0 ?? this.heat0,
      heat1: heat1 ?? this.heat1,
      heat2: heat2 ?? this.heat2,
      heat3: heat3 ?? this.heat3,
    );
  }

  @override
  QuadColors lerp(ThemeExtension<QuadColors>? other, double t) {
    if (other is! QuadColors) return this;
    return QuadColors(
      canvas: Color.lerp(canvas, other.canvas, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      surface2: Color.lerp(surface2, other.surface2, t)!,
      line: Color.lerp(line, other.line, t)!,
      lineStrong: Color.lerp(lineStrong, other.lineStrong, t)!,
      ink: Color.lerp(ink, other.ink, t)!,
      ink2: Color.lerp(ink2, other.ink2, t)!,
      ink3: Color.lerp(ink3, other.ink3, t)!,
      brand: Color.lerp(brand, other.brand, t)!,
      brandStrong: Color.lerp(brandStrong, other.brandStrong, t)!,
      brandSoft: Color.lerp(brandSoft, other.brandSoft, t)!,
      brandInk: Color.lerp(brandInk, other.brandInk, t)!,
      brandFill: Color.lerp(brandFill, other.brandFill, t)!,
      brandFillStrong: Color.lerp(brandFillStrong, other.brandFillStrong, t)!,
      rail: Color.lerp(rail, other.rail, t)!,
      rail2: Color.lerp(rail2, other.rail2, t)!,
      railInk: Color.lerp(railInk, other.railInk, t)!,
      railInk2: Color.lerp(railInk2, other.railInk2, t)!,
      railActive: Color.lerp(railActive, other.railActive, t)!,
      good: Color.lerp(good, other.good, t)!,
      goodSoft: Color.lerp(goodSoft, other.goodSoft, t)!,
      warn: Color.lerp(warn, other.warn, t)!,
      warnSoft: Color.lerp(warnSoft, other.warnSoft, t)!,
      bad: Color.lerp(bad, other.bad, t)!,
      badSoft: Color.lerp(badSoft, other.badSoft, t)!,
      info: Color.lerp(info, other.info, t)!,
      infoSoft: Color.lerp(infoSoft, other.infoSoft, t)!,
      c1: Color.lerp(c1, other.c1, t)!,
      c2: Color.lerp(c2, other.c2, t)!,
      c3: Color.lerp(c3, other.c3, t)!,
      c4: Color.lerp(c4, other.c4, t)!,
      c5: Color.lerp(c5, other.c5, t)!,
      gold: Color.lerp(gold, other.gold, t)!,
      goldSoft: Color.lerp(goldSoft, other.goldSoft, t)!,
      band: Color.lerp(band, other.band, t)!,
      band2: Color.lerp(band2, other.band2, t)!,
      bandInk: Color.lerp(bandInk, other.bandInk, t)!,
      bandInk2: Color.lerp(bandInk2, other.bandInk2, t)!,
      bandLine: Color.lerp(bandLine, other.bandLine, t)!,
      bandTagTealBg: Color.lerp(bandTagTealBg, other.bandTagTealBg, t)!,
      bandTagTealInk: Color.lerp(bandTagTealInk, other.bandTagTealInk, t)!,
      bandTagCoralBg: Color.lerp(bandTagCoralBg, other.bandTagCoralBg, t)!,
      bandTagCoralInk: Color.lerp(bandTagCoralInk, other.bandTagCoralInk, t)!,
      bandTagAmberBg: Color.lerp(bandTagAmberBg, other.bandTagAmberBg, t)!,
      bandTagAmberInk: Color.lerp(bandTagAmberInk, other.bandTagAmberInk, t)!,
      bandTagLilacBg: Color.lerp(bandTagLilacBg, other.bandTagLilacBg, t)!,
      bandTagLilacInk: Color.lerp(bandTagLilacInk, other.bandTagLilacInk, t)!,
      heat0: Color.lerp(heat0, other.heat0, t)!,
      heat1: Color.lerp(heat1, other.heat1, t)!,
      heat2: Color.lerp(heat2, other.heat2, t)!,
      heat3: Color.lerp(heat3, other.heat3, t)!,
    );
  }
}
