// GENERATED by pnpm tokens:build — do not edit

import 'package:flutter/material.dart';

/// Shape, space, elevation and font names. Colours live in [QuadColors].
class QuadTokens {
  const QuadTokens._();

  static const double radiusCard = 20;
  static const double radiusScene = 28;
  static const double radiusInput = 12;
  static const double radiusPill = 999;

  static const List<double> spacing = [
    4,
    6,
    8,
    10,
    12,
    14,
    16,
    18,
    20,
    24,
    28,
    32,
  ];

  static const List<BoxShadow> shadowSm = [
    BoxShadow(color: Color(0x0F101632), blurRadius: 2, offset: Offset(0, 1)),
  ];
  static const List<BoxShadow> shadowCard = [
    BoxShadow(color: Color(0x0D101632), blurRadius: 2, offset: Offset(0, 1)),
    BoxShadow(
      color: Color(0x4D101632),
      blurRadius: 28,
      spreadRadius: -18,
      offset: Offset(0, 10),
    ),
  ];
  static const List<BoxShadow> shadowLg = [
    BoxShadow(
      color: Color(0x73101632),
      blurRadius: 70,
      spreadRadius: -24,
      offset: Offset(0, 30),
    ),
  ];
  static const List<BoxShadow> shadowSmDark = [
    BoxShadow(color: Color(0x4D000000), blurRadius: 2, offset: Offset(0, 1)),
  ];
  static const List<BoxShadow> shadowCardDark = [
    BoxShadow(color: Color(0x4D000000), blurRadius: 2, offset: Offset(0, 1)),
    BoxShadow(
      color: Color(0xB3000000),
      blurRadius: 30,
      spreadRadius: -18,
      offset: Offset(0, 12),
    ),
  ];
  static const List<BoxShadow> shadowLgDark = [
    BoxShadow(
      color: Color(0xCC000000),
      blurRadius: 70,
      spreadRadius: -24,
      offset: Offset(0, 30),
    ),
  ];

  static const String fontSans = 'Figtree';
  static const String fontDisplay = 'Bricolage Grotesque';
}

/// Every colour of the Quad design system, one instance per theme.
/// Read it with `Theme.of(context).extension<QuadColors>()!`.
@immutable
class QuadColors extends ThemeExtension<QuadColors> {
  const QuadColors({
    required this.canvas,
    required this.surface,
    required this.surface2,
    required this.line,
    required this.lineStrong,
    required this.ink,
    required this.ink2,
    required this.ink3,
    required this.brand,
    required this.brandStrong,
    required this.brandSoft,
    required this.brandInk,
    required this.brandFill,
    required this.brandFillStrong,
    required this.rail,
    required this.rail2,
    required this.railInk,
    required this.railInk2,
    required this.railActive,
    required this.good,
    required this.goodSoft,
    required this.warn,
    required this.warnSoft,
    required this.bad,
    required this.badSoft,
    required this.info,
    required this.infoSoft,
    required this.c1,
    required this.c2,
    required this.c3,
    required this.c4,
    required this.c5,
    required this.gold,
    required this.goldSoft,
    required this.surface3,
    required this.fieldLine,
    required this.switchOff,
    required this.navy,
    required this.navy2,
    required this.navyLine,
    required this.onNavy,
    required this.onNavy2,
    required this.onNavy3,
    required this.navyCard,
    required this.navyCardRing,
    required this.inverse,
    required this.onInverse,
    required this.onFill,
    required this.railLine,
    required this.railActiveInk,
    required this.brandText,
    required this.brandRaw,
    required this.lime,
    required this.pink,
    required this.sky,
    required this.orange,
    required this.limeSoft,
    required this.pinkSoft,
    required this.skySoft,
    required this.orangeSoft,
    required this.limeInk,
    required this.pinkInk,
    required this.skyInk,
    required this.orangeInk,
    required this.goldInk,
    required this.heat0,
    required this.heat1,
    required this.heat2,
    required this.heat3,
    required this.heat0Ink,
    required this.heat1Ink,
    required this.heat2Ink,
    required this.heat3Ink,
    required this.focus,
    required this.navLime,
    required this.navOrange,
    required this.navPink,
    required this.navSky,
    required this.navViolet,
    required this.navMist,
  });

  final Color canvas;
  final Color surface;
  final Color surface2;
  final Color line;
  final Color lineStrong;
  final Color ink;
  final Color ink2;
  final Color ink3;
  final Color brand;
  final Color brandStrong;
  final Color brandSoft;
  final Color brandInk;
  final Color brandFill;
  final Color brandFillStrong;
  final Color rail;
  final Color rail2;
  final Color railInk;
  final Color railInk2;
  final Color railActive;
  final Color good;
  final Color goodSoft;
  final Color warn;
  final Color warnSoft;
  final Color bad;
  final Color badSoft;
  final Color info;
  final Color infoSoft;
  final Color c1;
  final Color c2;
  final Color c3;
  final Color c4;
  final Color c5;
  final Color gold;
  final Color goldSoft;
  final Color surface3;
  final Color fieldLine;
  final Color switchOff;
  final Color navy;
  final Color navy2;
  final Color navyLine;
  final Color onNavy;
  final Color onNavy2;
  final Color onNavy3;
  final Color navyCard;
  final Color navyCardRing;
  final Color inverse;
  final Color onInverse;
  final Color onFill;
  final Color railLine;
  final Color railActiveInk;
  final Color brandText;
  final Color brandRaw;
  final Color lime;
  final Color pink;
  final Color sky;
  final Color orange;
  final Color limeSoft;
  final Color pinkSoft;
  final Color skySoft;
  final Color orangeSoft;
  final Color limeInk;
  final Color pinkInk;
  final Color skyInk;
  final Color orangeInk;
  final Color goldInk;
  final Color heat0;
  final Color heat1;
  final Color heat2;
  final Color heat3;
  final Color heat0Ink;
  final Color heat1Ink;
  final Color heat2Ink;
  final Color heat3Ink;
  final Color focus;
  final Color navLime;
  final Color navOrange;
  final Color navPink;
  final Color navSky;
  final Color navViolet;
  final Color navMist;

  static const light = QuadColors(
    canvas: Color(0xFFF7F5F0),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFF0EEE7),
    line: Color(0xFFE4E1D8),
    lineStrong: Color(0xFFCDC8BA),
    ink: Color(0xFF101632),
    ink2: Color(0xFF3D4263),
    ink3: Color(0xFF5A5F7B),
    brand: Color(0xFFC8F169),
    brandStrong: Color(0xFFD0F37E),
    brandSoft: Color(0xFFF6FDE7),
    brandInk: Color(0xFF101632),
    brandFill: Color(0xFFC8F169),
    brandFillStrong: Color(0xFFD0F37E),
    rail: Color(0xFF101632),
    rail2: Color(0xFF1D2550),
    railInk: Color(0xFFF7F5F0),
    railInk2: Color(0xFFA9ACC8),
    railActive: Color(0xFFC8F169),
    good: Color(0xFF16703F),
    goodSoft: Color(0xFFDDF4E4),
    warn: Color(0xFFA04A00),
    warnSoft: Color(0xFFFFE9D3),
    bad: Color(0xFFC4234A),
    badSoft: Color(0xFFFFE3E9),
    info: Color(0xFF0B67A8),
    infoSoft: Color(0xFFDDF0FF),
    c1: Color(0xFFE0478A),
    c2: Color(0xFF4048B8),
    c3: Color(0xFF1F8ACF),
    c4: Color(0xFFD9640B),
    c5: Color(0xFF4E8A12),
    gold: Color(0xFFC8F169),
    goldSoft: Color(0xFFE6F6B5),
    surface3: Color(0xFFE8E5DC),
    fieldLine: Color(0xFF8E8A7D),
    switchOff: Color(0xFF8E8A7D),
    navy: Color(0xFF101632),
    navy2: Color(0xFF1D2550),
    navyLine: Color(0xFF2F3870),
    onNavy: Color(0xFFF7F5F0),
    onNavy2: Color(0xFFC9CBE0),
    onNavy3: Color(0xFFA9ACC8),
    navyCard: Color(0xFF101632),
    navyCardRing: Color(0x00000000),
    inverse: Color(0xFF101632),
    onInverse: Color(0xFFF7F5F0),
    onFill: Color(0xFFFFFFFF),
    railLine: Color(0xFF2A3266),
    railActiveInk: Color(0xFF101632),
    brandText: Color(0xFF5E7131),
    brandRaw: Color(0xFFC8F169),
    lime: Color(0xFFC8F169),
    pink: Color(0xFFFF6FAE),
    sky: Color(0xFF59C3FF),
    orange: Color(0xFFFF9B45),
    limeSoft: Color(0xFFEDF8CC),
    pinkSoft: Color(0xFFFFE3EF),
    skySoft: Color(0xFFDCF1FF),
    orangeSoft: Color(0xFFFFE8D2),
    limeInk: Color(0xFF3D5410),
    pinkInk: Color(0xFF8A1D4C),
    skyInk: Color(0xFF0D4F7A),
    orangeInk: Color(0xFF7A3A07),
    goldInk: Color(0xFF3D5410),
    heat0: Color(0xFFFFD4E7),
    heat1: Color(0xFFECFACB),
    heat2: Color(0xFFDBF69E),
    heat3: Color(0xFFC8F169),
    heat0Ink: Color(0xFF101632),
    heat1Ink: Color(0xFF101632),
    heat2Ink: Color(0xFF101632),
    heat3Ink: Color(0xFF101632),
    focus: Color(0xFF2F6BFF),
    navLime: Color(0xFFC8F169),
    navOrange: Color(0xFFFF9B45),
    navPink: Color(0xFFFF6FAE),
    navSky: Color(0xFF59C3FF),
    navViolet: Color(0xFF8C93FF),
    navMist: Color(0xFFC9CBE0),
  );

  static const dark = QuadColors(
    canvas: Color(0xFF0F1330),
    surface: Color(0xFF171D45),
    surface2: Color(0xFF1D2550),
    line: Color(0xFF2A3266),
    lineStrong: Color(0xFF3A4378),
    ink: Color(0xFFF7F5F0),
    ink2: Color(0xFFC9CBE0),
    ink3: Color(0xFFA9ACC8),
    brand: Color(0xFFC8F169),
    brandStrong: Color(0xFFD0F37E),
    brandSoft: Color(0xFF37434B),
    brandInk: Color(0xFF101632),
    brandFill: Color(0xFFC8F169),
    brandFillStrong: Color(0xFFD0F37E),
    rail: Color(0xFF0A0D24),
    rail2: Color(0xFF161C48),
    railInk: Color(0xFFF7F5F0),
    railInk2: Color(0xFFA9ACC8),
    railActive: Color(0xFFC8F169),
    good: Color(0xFF5FD394),
    goodSoft: Color(0xFF12382A),
    warn: Color(0xFFFFB066),
    warnSoft: Color(0xFF3D2610),
    bad: Color(0xFFFF7C9C),
    badSoft: Color(0xFF401A2A),
    info: Color(0xFF7CCBFF),
    infoSoft: Color(0xFF12304F),
    c1: Color(0xFFFF6FAE),
    c2: Color(0xFF8C93FF),
    c3: Color(0xFF59C3FF),
    c4: Color(0xFFFF9B45),
    c5: Color(0xFFC8F169),
    gold: Color(0xFFC8F169),
    goldSoft: Color(0xFF41504E),
    surface3: Color(0xFF242C5C),
    fieldLine: Color(0xFF636DAA),
    switchOff: Color(0xFF636DAA),
    navy: Color(0xFF101632),
    navy2: Color(0xFF1D2550),
    navyLine: Color(0xFF2F3870),
    onNavy: Color(0xFFF7F5F0),
    onNavy2: Color(0xFFC9CBE0),
    onNavy3: Color(0xFFA9ACC8),
    navyCard: Color(0xFF1D2550),
    navyCardRing: Color(0xFF2F3870),
    inverse: Color(0xFFF7F5F0),
    onInverse: Color(0xFF101632),
    onFill: Color(0xFF101632),
    railLine: Color(0xFF232A5C),
    railActiveInk: Color(0xFF101632),
    brandText: Color(0xFFC8F169),
    brandRaw: Color(0xFFC8F169),
    lime: Color(0xFFC8F169),
    pink: Color(0xFFFF6FAE),
    sky: Color(0xFF59C3FF),
    orange: Color(0xFFFF9B45),
    limeSoft: Color(0xFF37434B),
    pinkSoft: Color(0xFF452D5A),
    skySoft: Color(0xFF243E6A),
    orangeSoft: Color(0xFF453645),
    limeInk: Color(0xFFD8F59A),
    pinkInk: Color(0xFFFFB3D3),
    skyInk: Color(0xFFA8DDFF),
    orangeInk: Color(0xFFFFC694),
    goldInk: Color(0xFFD8F59A),
    heat0: Color(0xFF683A6A),
    heat1: Color(0xFF4C5D50),
    heat2: Color(0xFF819C5B),
    heat3: Color(0xFFC8F169),
    heat0Ink: Color(0xFFF7F5F0),
    heat1Ink: Color(0xFFF7F5F0),
    heat2Ink: Color(0xFF101632),
    heat3Ink: Color(0xFF101632),
    focus: Color(0xFF7FA6FF),
    navLime: Color(0xFFC8F169),
    navOrange: Color(0xFFFF9B45),
    navPink: Color(0xFFFF6FAE),
    navSky: Color(0xFF59C3FF),
    navViolet: Color(0xFF8C93FF),
    navMist: Color(0xFFC9CBE0),
  );

  @override
  QuadColors copyWith({
    Color? canvas,
    Color? surface,
    Color? surface2,
    Color? line,
    Color? lineStrong,
    Color? ink,
    Color? ink2,
    Color? ink3,
    Color? brand,
    Color? brandStrong,
    Color? brandSoft,
    Color? brandInk,
    Color? brandFill,
    Color? brandFillStrong,
    Color? rail,
    Color? rail2,
    Color? railInk,
    Color? railInk2,
    Color? railActive,
    Color? good,
    Color? goodSoft,
    Color? warn,
    Color? warnSoft,
    Color? bad,
    Color? badSoft,
    Color? info,
    Color? infoSoft,
    Color? c1,
    Color? c2,
    Color? c3,
    Color? c4,
    Color? c5,
    Color? gold,
    Color? goldSoft,
    Color? surface3,
    Color? fieldLine,
    Color? switchOff,
    Color? navy,
    Color? navy2,
    Color? navyLine,
    Color? onNavy,
    Color? onNavy2,
    Color? onNavy3,
    Color? navyCard,
    Color? navyCardRing,
    Color? inverse,
    Color? onInverse,
    Color? onFill,
    Color? railLine,
    Color? railActiveInk,
    Color? brandText,
    Color? brandRaw,
    Color? lime,
    Color? pink,
    Color? sky,
    Color? orange,
    Color? limeSoft,
    Color? pinkSoft,
    Color? skySoft,
    Color? orangeSoft,
    Color? limeInk,
    Color? pinkInk,
    Color? skyInk,
    Color? orangeInk,
    Color? goldInk,
    Color? heat0,
    Color? heat1,
    Color? heat2,
    Color? heat3,
    Color? heat0Ink,
    Color? heat1Ink,
    Color? heat2Ink,
    Color? heat3Ink,
    Color? focus,
    Color? navLime,
    Color? navOrange,
    Color? navPink,
    Color? navSky,
    Color? navViolet,
    Color? navMist,
  }) {
    return QuadColors(
      canvas: canvas ?? this.canvas,
      surface: surface ?? this.surface,
      surface2: surface2 ?? this.surface2,
      line: line ?? this.line,
      lineStrong: lineStrong ?? this.lineStrong,
      ink: ink ?? this.ink,
      ink2: ink2 ?? this.ink2,
      ink3: ink3 ?? this.ink3,
      brand: brand ?? this.brand,
      brandStrong: brandStrong ?? this.brandStrong,
      brandSoft: brandSoft ?? this.brandSoft,
      brandInk: brandInk ?? this.brandInk,
      brandFill: brandFill ?? this.brandFill,
      brandFillStrong: brandFillStrong ?? this.brandFillStrong,
      rail: rail ?? this.rail,
      rail2: rail2 ?? this.rail2,
      railInk: railInk ?? this.railInk,
      railInk2: railInk2 ?? this.railInk2,
      railActive: railActive ?? this.railActive,
      good: good ?? this.good,
      goodSoft: goodSoft ?? this.goodSoft,
      warn: warn ?? this.warn,
      warnSoft: warnSoft ?? this.warnSoft,
      bad: bad ?? this.bad,
      badSoft: badSoft ?? this.badSoft,
      info: info ?? this.info,
      infoSoft: infoSoft ?? this.infoSoft,
      c1: c1 ?? this.c1,
      c2: c2 ?? this.c2,
      c3: c3 ?? this.c3,
      c4: c4 ?? this.c4,
      c5: c5 ?? this.c5,
      gold: gold ?? this.gold,
      goldSoft: goldSoft ?? this.goldSoft,
      surface3: surface3 ?? this.surface3,
      fieldLine: fieldLine ?? this.fieldLine,
      switchOff: switchOff ?? this.switchOff,
      navy: navy ?? this.navy,
      navy2: navy2 ?? this.navy2,
      navyLine: navyLine ?? this.navyLine,
      onNavy: onNavy ?? this.onNavy,
      onNavy2: onNavy2 ?? this.onNavy2,
      onNavy3: onNavy3 ?? this.onNavy3,
      navyCard: navyCard ?? this.navyCard,
      navyCardRing: navyCardRing ?? this.navyCardRing,
      inverse: inverse ?? this.inverse,
      onInverse: onInverse ?? this.onInverse,
      onFill: onFill ?? this.onFill,
      railLine: railLine ?? this.railLine,
      railActiveInk: railActiveInk ?? this.railActiveInk,
      brandText: brandText ?? this.brandText,
      brandRaw: brandRaw ?? this.brandRaw,
      lime: lime ?? this.lime,
      pink: pink ?? this.pink,
      sky: sky ?? this.sky,
      orange: orange ?? this.orange,
      limeSoft: limeSoft ?? this.limeSoft,
      pinkSoft: pinkSoft ?? this.pinkSoft,
      skySoft: skySoft ?? this.skySoft,
      orangeSoft: orangeSoft ?? this.orangeSoft,
      limeInk: limeInk ?? this.limeInk,
      pinkInk: pinkInk ?? this.pinkInk,
      skyInk: skyInk ?? this.skyInk,
      orangeInk: orangeInk ?? this.orangeInk,
      goldInk: goldInk ?? this.goldInk,
      heat0: heat0 ?? this.heat0,
      heat1: heat1 ?? this.heat1,
      heat2: heat2 ?? this.heat2,
      heat3: heat3 ?? this.heat3,
      heat0Ink: heat0Ink ?? this.heat0Ink,
      heat1Ink: heat1Ink ?? this.heat1Ink,
      heat2Ink: heat2Ink ?? this.heat2Ink,
      heat3Ink: heat3Ink ?? this.heat3Ink,
      focus: focus ?? this.focus,
      navLime: navLime ?? this.navLime,
      navOrange: navOrange ?? this.navOrange,
      navPink: navPink ?? this.navPink,
      navSky: navSky ?? this.navSky,
      navViolet: navViolet ?? this.navViolet,
      navMist: navMist ?? this.navMist,
    );
  }

  @override
  QuadColors lerp(ThemeExtension<QuadColors>? other, double t) {
    if (other is! QuadColors) return this;
    return QuadColors(
      canvas: Color.lerp(canvas, other.canvas, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      surface2: Color.lerp(surface2, other.surface2, t)!,
      line: Color.lerp(line, other.line, t)!,
      lineStrong: Color.lerp(lineStrong, other.lineStrong, t)!,
      ink: Color.lerp(ink, other.ink, t)!,
      ink2: Color.lerp(ink2, other.ink2, t)!,
      ink3: Color.lerp(ink3, other.ink3, t)!,
      brand: Color.lerp(brand, other.brand, t)!,
      brandStrong: Color.lerp(brandStrong, other.brandStrong, t)!,
      brandSoft: Color.lerp(brandSoft, other.brandSoft, t)!,
      brandInk: Color.lerp(brandInk, other.brandInk, t)!,
      brandFill: Color.lerp(brandFill, other.brandFill, t)!,
      brandFillStrong: Color.lerp(brandFillStrong, other.brandFillStrong, t)!,
      rail: Color.lerp(rail, other.rail, t)!,
      rail2: Color.lerp(rail2, other.rail2, t)!,
      railInk: Color.lerp(railInk, other.railInk, t)!,
      railInk2: Color.lerp(railInk2, other.railInk2, t)!,
      railActive: Color.lerp(railActive, other.railActive, t)!,
      good: Color.lerp(good, other.good, t)!,
      goodSoft: Color.lerp(goodSoft, other.goodSoft, t)!,
      warn: Color.lerp(warn, other.warn, t)!,
      warnSoft: Color.lerp(warnSoft, other.warnSoft, t)!,
      bad: Color.lerp(bad, other.bad, t)!,
      badSoft: Color.lerp(badSoft, other.badSoft, t)!,
      info: Color.lerp(info, other.info, t)!,
      infoSoft: Color.lerp(infoSoft, other.infoSoft, t)!,
      c1: Color.lerp(c1, other.c1, t)!,
      c2: Color.lerp(c2, other.c2, t)!,
      c3: Color.lerp(c3, other.c3, t)!,
      c4: Color.lerp(c4, other.c4, t)!,
      c5: Color.lerp(c5, other.c5, t)!,
      gold: Color.lerp(gold, other.gold, t)!,
      goldSoft: Color.lerp(goldSoft, other.goldSoft, t)!,
      surface3: Color.lerp(surface3, other.surface3, t)!,
      fieldLine: Color.lerp(fieldLine, other.fieldLine, t)!,
      switchOff: Color.lerp(switchOff, other.switchOff, t)!,
      navy: Color.lerp(navy, other.navy, t)!,
      navy2: Color.lerp(navy2, other.navy2, t)!,
      navyLine: Color.lerp(navyLine, other.navyLine, t)!,
      onNavy: Color.lerp(onNavy, other.onNavy, t)!,
      onNavy2: Color.lerp(onNavy2, other.onNavy2, t)!,
      onNavy3: Color.lerp(onNavy3, other.onNavy3, t)!,
      navyCard: Color.lerp(navyCard, other.navyCard, t)!,
      navyCardRing: Color.lerp(navyCardRing, other.navyCardRing, t)!,
      inverse: Color.lerp(inverse, other.inverse, t)!,
      onInverse: Color.lerp(onInverse, other.onInverse, t)!,
      onFill: Color.lerp(onFill, other.onFill, t)!,
      railLine: Color.lerp(railLine, other.railLine, t)!,
      railActiveInk: Color.lerp(railActiveInk, other.railActiveInk, t)!,
      brandText: Color.lerp(brandText, other.brandText, t)!,
      brandRaw: Color.lerp(brandRaw, other.brandRaw, t)!,
      lime: Color.lerp(lime, other.lime, t)!,
      pink: Color.lerp(pink, other.pink, t)!,
      sky: Color.lerp(sky, other.sky, t)!,
      orange: Color.lerp(orange, other.orange, t)!,
      limeSoft: Color.lerp(limeSoft, other.limeSoft, t)!,
      pinkSoft: Color.lerp(pinkSoft, other.pinkSoft, t)!,
      skySoft: Color.lerp(skySoft, other.skySoft, t)!,
      orangeSoft: Color.lerp(orangeSoft, other.orangeSoft, t)!,
      limeInk: Color.lerp(limeInk, other.limeInk, t)!,
      pinkInk: Color.lerp(pinkInk, other.pinkInk, t)!,
      skyInk: Color.lerp(skyInk, other.skyInk, t)!,
      orangeInk: Color.lerp(orangeInk, other.orangeInk, t)!,
      goldInk: Color.lerp(goldInk, other.goldInk, t)!,
      heat0: Color.lerp(heat0, other.heat0, t)!,
      heat1: Color.lerp(heat1, other.heat1, t)!,
      heat2: Color.lerp(heat2, other.heat2, t)!,
      heat3: Color.lerp(heat3, other.heat3, t)!,
      heat0Ink: Color.lerp(heat0Ink, other.heat0Ink, t)!,
      heat1Ink: Color.lerp(heat1Ink, other.heat1Ink, t)!,
      heat2Ink: Color.lerp(heat2Ink, other.heat2Ink, t)!,
      heat3Ink: Color.lerp(heat3Ink, other.heat3Ink, t)!,
      focus: Color.lerp(focus, other.focus, t)!,
      navLime: Color.lerp(navLime, other.navLime, t)!,
      navOrange: Color.lerp(navOrange, other.navOrange, t)!,
      navPink: Color.lerp(navPink, other.navPink, t)!,
      navSky: Color.lerp(navSky, other.navSky, t)!,
      navViolet: Color.lerp(navViolet, other.navViolet, t)!,
      navMist: Color.lerp(navMist, other.navMist, t)!,
    );
  }
}
